--vim.g.nvim_tree_show_icons = {git = 1, folders = 1, files = 1}
--vim.g.nvim_tree_icons = {
--    default = '',
--    symlink = '',
--    git = {unstaged = "✗", staged = "✓", unmerged = "", renamed = "➜", untracked = "",ignored	= "◌"},
--    folder = {arrow_open = "-",  arrow_closed = "|", default = "📁", open = "📂", empty = "", empty_open = "", symlink = "🔗"}
--} 
